schema_version: 1

context:
  version: "0.6.0"

package:
  name: otel-tui
  version: ${{ version }}

source:
  url: https://github.com/ymtdzzz/otel-tui/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 17d1f5f96c5f2b42d81144540ac5a38abe3af7a088e26d16db2e5e9dda352d08
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/apache/thrift  --ignore github.com/jmespath/go-jmespath --ignore github.com/ymtdzzz/otel-tui/tuiexporter
    - if: unix
      then: |
        go build -ldflags="-s -w" -v -o $PREFIX/bin/otel-tui
        cp -r ${RECIPE_DIR}/library_licenses/* ${SRC_DIR}/library_licenses
      else: |
        go build -ldflags="-s -w" -v -o %LIBRARY_BIN%\otel-tui.exe
        xcopy /s %RECIPE_DIR%\library_licenses\* %SRC_DIR%\library_licenses
requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - make
    - go-licenses >=2.0
    - if: unix
      then: pandoc

tests:
  - script:
      - otel-tui --help

about:
  summary: A terminal OpenTelemetry viewer inspired by otel-desktop-viewer
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  homepage: https://github.com/ymtdzzz/otel-tui
  repository: https://github.com/ymtdzzz/otel-tui

extra:
  recipe-maintainers:
    - moritzwilksch
